version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: light-salt-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t3_skeleton_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      target: development
    container_name: light-salt-api
    ports:
      - "5000:5000"
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/light_salt_db
      FRONTEND_URL: http://localhost:8080
    depends_on:
      - postgres

  web:
    image: node:20-alpine
    container_name: light-salt-web
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "8080:8080"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000/api/v1
      VITE_PORT: 8080
      VITE_APP_NAME: Light & Salt Marketplace
    depends_on:
      - api

volumes:
  pgdata:
