version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: t3-skeleton-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t3_skeleton
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: development
    container_name: t3-skeleton-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/t3_skeleton
      FRONTEND_URL: http://localhost:8080
    depends_on:
      - postgres


  # Frontend (Vite Dev Server)
  frontend:
    image: node:20-alpine
    container_name: t3-skeleton-frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000/api/v1
      VITE_PORT: 8080
      VITE_APP_NAME: T3 Skeleton Frontend
    depends_on:
      - backend


volumes:
  pgdata:
